apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000  # External port
      targetPort: 8000  # Pod's container port
Nodeport: 31924

  type: LoadBalancer
